/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_TextureProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_TextureProxy
#define _Included_com_radiance_client_proxy_vulkan_TextureProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    generateTextureId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_generateTextureId
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    prepareImage
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_prepareImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    setFilter
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_setFilter
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    setClamp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_setClamp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    queueUpload
 * Signature: (JIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_queueUpload
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    setTextureAlphaClass
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_setTextureAlphaClass
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
