/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_WindowProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_WindowProxy
#define _Included_com_radiance_client_proxy_vulkan_WindowProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_WindowProxy
 * Method:    onFramebufferSizeChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_WindowProxy_onFramebufferSizeChanged
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
