/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_RendererProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_RendererProxy
#define _Included_com_radiance_client_proxy_vulkan_RendererProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    initFolderPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_initFolderPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    initRenderer
 * Signature: ([Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_initRenderer
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    maxSupportedTextureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_maxSupportedTextureSize
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    acquireContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_acquireContext
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    submitCommand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_submitCommand
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    present
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_present
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    drawOverlay
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_drawOverlay
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    fuseWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_fuseWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    postBlur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_postBlur
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_close
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    shouldRenderWorld
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_shouldRenderWorld
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    takeScreenshot
 * Signature: (ZIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_takeScreenshot
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    takeScreenshotRawHdrPacked
 * Signature: (ZIIJI)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_takeScreenshotRawHdrPacked
  (JNIEnv *, jclass, jboolean, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
