/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState */

#ifndef _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
#define _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024RasterizationState_setLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
 * Method:    vkSetPolygonMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024RasterizationState_vkSetPolygonMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
 * Method:    vkSetCullMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024RasterizationState_vkSetCullMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
 * Method:    vkSetFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024RasterizationState_vkSetFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
 * Method:    vkSetDepthBiasEnable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024RasterizationState_vkSetDepthBiasEnable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_RasterizationState
 * Method:    vkSetDepthBias
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024RasterizationState_vkSetDepthBias
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
