/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState */

#ifndef _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
#define _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    setBlendEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_setBlendEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    setColorBlendConstants
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_setColorBlendConstants
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    setColorLogicOpEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_setColorLogicOpEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    vkSetBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_vkSetBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    vkSetBlendOpSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_vkSetBlendOpSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    vkSetColorWriteMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_vkSetColorWriteMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ColorBlendState
 * Method:    vkSetColorLogicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ColorBlendState_vkSetColorLogicOp
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
