/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_DrawCommandProxy_Overlay */

#ifndef _Included_com_radiance_client_proxy_vulkan_DrawCommandProxy_Overlay
#define _Included_com_radiance_client_proxy_vulkan_DrawCommandProxy_Overlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_DrawCommandProxy_Overlay
 * Method:    vkCmdClearEntireColorAttachment
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_DrawCommandProxy_00024Overlay_vkCmdClearEntireColorAttachment
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_DrawCommandProxy_Overlay
 * Method:    vkCmdClearEntireDepthStencilAttachment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_DrawCommandProxy_00024Overlay_vkCmdClearEntireDepthStencilAttachment
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
