/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_PipelineStateProxy_ClearState */

#ifndef _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_ClearState
#define _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_ClearState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ClearState
 * Method:    setClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ClearState_setClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ClearState
 * Method:    setClearDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ClearState_setClearDepth
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ClearState
 * Method:    setClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ClearState_setClearStencil
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
