/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_BufferProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_BufferProxy
#define _Included_com_radiance_client_proxy_vulkan_BufferProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    allocateBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_allocateBuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    initializeBuffer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_initializeBuffer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    buildIndexBuffer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_buildIndexBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    queueUpload
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_queueUpload
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    performQueuedUpload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_performQueuedUpload
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    updateOverlayDrawUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_updateOverlayDrawUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    updateOverlayPostUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_updateOverlayPostUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    updateWorldUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_updateWorldUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    updateSkyUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_updateSkyUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    updateMapping
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_updateMapping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_BufferProxy
 * Method:    updateLightMapUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_BufferProxy_updateLightMapUniform
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
