/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_option_Options */

#ifndef _Included_com_radiance_client_option_Options
#define _Included_com_radiance_client_option_Options
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_option_Options_CURRENT_OPTIONS_VERSION
#define com_radiance_client_option_Options_CURRENT_OPTIONS_VERSION 13L
#undef com_radiance_client_option_Options_SDR_TONEMAPPING_DEFAULT_MODE
#define com_radiance_client_option_Options_SDR_TONEMAPPING_DEFAULT_MODE 1L
#undef com_radiance_client_option_Options_SATURATION_DEFAULT_PERCENT
#define com_radiance_client_option_Options_SATURATION_DEFAULT_PERCENT 130L
#undef com_radiance_client_option_Options_SDR_TRANSFER_FUNCTION_GAMMA_22
#define com_radiance_client_option_Options_SDR_TRANSFER_FUNCTION_GAMMA_22 0L
#undef com_radiance_client_option_Options_SDR_TRANSFER_FUNCTION_SRGB
#define com_radiance_client_option_Options_SDR_TRANSFER_FUNCTION_SRGB 1L
#undef com_radiance_client_option_Options_DIM_OVERWORLD
#define com_radiance_client_option_Options_DIM_OVERWORLD 0L
#undef com_radiance_client_option_Options_DIM_NETHER
#define com_radiance_client_option_Options_DIM_NETHER 1L
#undef com_radiance_client_option_Options_DIM_END
#define com_radiance_client_option_Options_DIM_END 2L
#undef com_radiance_client_option_Options_DIM_COUNT
#define com_radiance_client_option_Options_DIM_COUNT 3L
#undef com_radiance_client_option_Options_PERCENT_DEFAULT
#define com_radiance_client_option_Options_PERCENT_DEFAULT 100L
#undef com_radiance_client_option_Options_MOON_INTENSITY_DEFAULT_OVERWORLD_PERCENT
#define com_radiance_client_option_Options_MOON_INTENSITY_DEFAULT_OVERWORLD_PERCENT 10L
#undef com_radiance_client_option_Options_WATER_TINT_R_DEFAULT
#define com_radiance_client_option_Options_WATER_TINT_R_DEFAULT 0L
#undef com_radiance_client_option_Options_WATER_TINT_G_DEFAULT
#define com_radiance_client_option_Options_WATER_TINT_G_DEFAULT 48L
#undef com_radiance_client_option_Options_WATER_TINT_B_DEFAULT
#define com_radiance_client_option_Options_WATER_TINT_B_DEFAULT 65L
#undef com_radiance_client_option_Options_CLOUD_DETAIL_SCALE_DEFAULT_PERCENT
#define com_radiance_client_option_Options_CLOUD_DETAIL_SCALE_DEFAULT_PERCENT 100L
#undef com_radiance_client_option_Options_CLOUD_DETAIL_STRENGTH_DEFAULT_PERCENT
#define com_radiance_client_option_Options_CLOUD_DETAIL_STRENGTH_DEFAULT_PERCENT 100L
#undef com_radiance_client_option_Options_SUN_PATH_MODE_DEFAULT
#define com_radiance_client_option_Options_SUN_PATH_MODE_DEFAULT 1L
#undef com_radiance_client_option_Options_SUN_INCLINATION_DEFAULT
#define com_radiance_client_option_Options_SUN_INCLINATION_DEFAULT 23L
#undef com_radiance_client_option_Options_SUN_AZIMUTH_OFFSET_DEFAULT
#define com_radiance_client_option_Options_SUN_AZIMUTH_OFFSET_DEFAULT 0L
#undef com_radiance_client_option_Options_MOON_INCLINATION_DEFAULT
#define com_radiance_client_option_Options_MOON_INCLINATION_DEFAULT 23L
#undef com_radiance_client_option_Options_MOON_AZIMUTH_OFFSET_DEFAULT
#define com_radiance_client_option_Options_MOON_AZIMUTH_OFFSET_DEFAULT 0L
/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetMaxFps
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetMaxFps
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetInactivityFpsLimit
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetInactivityFpsLimit
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetVsync
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetVsync
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetChunkBuildingBatchSize
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetChunkBuildingBatchSize
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetChunkBuildingTotalBatches
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetChunkBuildingTotalBatches
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetTonemappingMode
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetTonemappingMode
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetSdrTransferFunction
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetSdrTransferFunction
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetDlssQuality
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetDlssQuality
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetDlssResOverride
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetDlssResOverride
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetRayBounces
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetRayBounces
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetOMMEnabled
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetOMMEnabled
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetOMMBakerLevel
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetOMMBakerLevel
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetSimplifiedIndirect
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetSimplifiedIndirect
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetOutputScale2x
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetOutputScale2x
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetReflexEnabled
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetReflexEnabled
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetReflexBoost
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetReflexBoost
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeIsReflexSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_option_Options_nativeIsReflexSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetVrrMode
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetVrrMode
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeGetDisplayRefreshRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_option_Options_nativeGetDisplayRefreshRate
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetMinExposure
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetMinExposure
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetMaxExposure
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetMaxExposure
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetDlssPreset
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetDlssPreset
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureCompensation
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureCompensation
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetManualExposureEnabled
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetManualExposureEnabled
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetManualExposure
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetManualExposure
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetCasEnabled
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetCasEnabled
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetCasSharpness
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetCasSharpness
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetMiddleGrey
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetMiddleGrey
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetLegacyExposure
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetLegacyExposure
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureUpSpeed
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureUpSpeed
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureDownSpeed
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureDownSpeed
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureBrightAdaptBoost
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureBrightAdaptBoost
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureHighlightProtection
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureHighlightProtection
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureHighlightPercentile
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureHighlightPercentile
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureHighlightSmoothingSpeed
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureHighlightSmoothingSpeed
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetExposureLog2MaxImproved
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetExposureLog2MaxImproved
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetLwhite
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetLwhite
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetSaturation
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetSaturation
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetHdrEnabled
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetHdrEnabled
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetHdrPeakNits
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetHdrPeakNits
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetHdrPaperWhiteNits
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetHdrPaperWhiteNits
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetHdrUiBrightnessNits
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetHdrUiBrightnessNits
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeIsHdrActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_option_Options_nativeIsHdrActive
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeIsHdrSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_option_Options_nativeIsHdrSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeRebuildChunks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeRebuildChunks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
