/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_world_ChunkProxy */

#ifndef _Included_com_radiance_client_proxy_world_ChunkProxy
#define _Included_com_radiance_client_proxy_world_ChunkProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_world_ChunkProxy_numNormalChunkRebuildThreads
#define com_radiance_client_proxy_world_ChunkProxy_numNormalChunkRebuildThreads 1L
#undef com_radiance_client_proxy_world_ChunkProxy_numImportantChunkRebuildThreads
#define com_radiance_client_proxy_world_ChunkProxy_numImportantChunkRebuildThreads 1L
#undef com_radiance_client_proxy_world_ChunkProxy_maxImportantTasksPerFrameWarmup
#define com_radiance_client_proxy_world_ChunkProxy_maxImportantTasksPerFrameWarmup 1L
#undef com_radiance_client_proxy_world_ChunkProxy_maxImportantTasksPerFrameNormal
#define com_radiance_client_proxy_world_ChunkProxy_maxImportantTasksPerFrameNormal 1L
#undef com_radiance_client_proxy_world_ChunkProxy_importantDistanceSqWarmup
#define com_radiance_client_proxy_world_ChunkProxy_importantDistanceSqWarmup 256.0
#undef com_radiance_client_proxy_world_ChunkProxy_importantDistanceSqNormal
#define com_radiance_client_proxy_world_ChunkProxy_importantDistanceSqNormal 768.0
/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    initNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_initNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    rebuildSingle
 * Signature: (IIIJIJJJJJZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_rebuildSingle
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint, jlong, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    isChunkReady
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_isChunkReady
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    invalidateSingle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_invalidateSingle
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
