/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_PipelineStateProxy_ViewportState */

#ifndef _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_ViewportState
#define _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_ViewportState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ViewportState
 * Method:    setScissorEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ViewportState_setScissorEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ViewportState
 * Method:    setScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ViewportState_setScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_ViewportState
 * Method:    setViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024ViewportState_setViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
