/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_world_EntityProxy */

#ifndef _Included_com_radiance_client_proxy_world_EntityProxy
#define _Included_com_radiance_client_proxy_world_EntityProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_world_EntityProxy_DEFAULT_WORLD_ENTITY_BUFFER_SIZE
#define com_radiance_client_proxy_world_EntityProxy_DEFAULT_WORLD_ENTITY_BUFFER_SIZE 786432L
#undef com_radiance_client_proxy_world_EntityProxy_BLOCK_ENTITY_BUFFER_SIZE
#define com_radiance_client_proxy_world_EntityProxy_BLOCK_ENTITY_BUFFER_SIZE 131072L
#undef com_radiance_client_proxy_world_EntityProxy_BLOCK_CRUMBLING_BUFFER_SIZE
#define com_radiance_client_proxy_world_EntityProxy_BLOCK_CRUMBLING_BUFFER_SIZE 65536L
#undef com_radiance_client_proxy_world_EntityProxy_BLOCK_ENTITY_RENDER_DISTANCE_SQ
#define com_radiance_client_proxy_world_EntityProxy_BLOCK_ENTITY_RENDER_DISTANCE_SQ 9216.0
/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    queueBuild
 * Signature: (FIZIJJJJJJJJJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_queueBuild
  (JNIEnv *, jclass, jfloat, jint, jboolean, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    build
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_build
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
